//! End-to-end fetch-path benchmarks for the SQLite backend.
//!
//! Goes through the full FFI path: alloc handles -> connect (`:memory:`) ->
//! exec_direct -> fetch -> {bind_col | get_data} -> cleanup. Catches the
//! eager-materialize + per-call clone cost in the SqliteBackend → ColumnValue
//! → write_column_value pipeline.
//!
//! Two workload shapes, matching core's own fetch-throughput benchmark:
//!   * Shape A: mixed columns (BENCH_ROWS × BENCH_COLS, 50/40/10 i64/str/decimal)
//!   * Shape B: 5 columns × BENCH_WIDE_STR_LEN-char strings (BENCH_WIDE_ROWS rows)
//!
//! Three scenarios:
//!   * late_binding: SQLFetch + per-cell SQLGetData
//!   * bound_columns: SQLBindCol + SQLFetch
//!   * repeat_get_data: SQLGetData called BENCH_REPEAT_GET_DATA times per cell
//!
//! Run:
//!   cargo bench
//!   BENCH_ROWS=1000000 cargo bench

use std::ffi::c_void;
use std::hint::black_box;
use std::time::Duration;

use criterion::{BatchSize, BenchmarkId, Criterion, Throughput, criterion_group, criterion_main};
use stackable_odbc_core::ffi;
use stackable_odbc_core::types::{CDataType, HandleType, SqlReturn};
use stackable_odbc_sqlite::SqliteBackend;

#[derive(Clone, Copy)]
struct BenchConfig {
    rows: usize,
    cols: usize,
    wide_rows: usize,
    wide_str_len: usize,
    repeat_get_data: usize,
}

fn env_or<T: std::str::FromStr>(name: &str, default: T) -> T {
    std::env::var(name)
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(default)
}

fn bench_config() -> BenchConfig {
    BenchConfig {
        rows: env_or("BENCH_ROWS", 100_000),
        cols: env_or("BENCH_COLS", 20),
        wide_rows: env_or("BENCH_WIDE_ROWS", 10_000),
        wide_str_len: env_or("BENCH_WIDE_STR_LEN", 1024),
        repeat_get_data: env_or("BENCH_REPEAT_GET_DATA", 3),
    }
}

fn configure_for_size(c: Criterion, rows: usize) -> Criterion {
    if rows > 250_000 {
        c.sample_size(20)
            .measurement_time(Duration::from_secs(30))
            .warm_up_time(Duration::from_secs(3))
    } else {
        c
    }
}

fn shape_a_split(n_cols: usize) -> (usize, usize, usize) {
    let s = (n_cols * 4) / 10;
    let d = n_cols / 10;
    let i = n_cols - s - d;
    debug_assert_eq!(i + s + d, n_cols, "shape_a_split must total n_cols");
    (i, s, d)
}

/// Allocate env + conn + stmt handles. Caller must call `cleanup` exactly once.
unsafe fn alloc_handles() -> (*mut c_void, *mut c_void, *mut c_void) {
    unsafe {
        let mut env: *mut c_void = std::ptr::null_mut();
        let _ = ffi::handle::sql_alloc_handle::<SqliteBackend>(
            HandleType::Env as i16,
            std::ptr::null_mut(),
            &mut env,
        );
        let mut conn: *mut c_void = std::ptr::null_mut();
        let _ =
            ffi::handle::sql_alloc_handle::<SqliteBackend>(HandleType::Dbc as i16, env, &mut conn);
        let mut stmt: *mut c_void = std::ptr::null_mut();
        let _ = ffi::handle::sql_alloc_handle::<SqliteBackend>(
            HandleType::Stmt as i16,
            conn,
            &mut stmt,
        );
        (env, conn, stmt)
    }
}

unsafe fn connect_memory(conn: *mut c_void) -> SqlReturn {
    unsafe {
        let wide: Vec<u16> = "Database=:memory:".encode_utf16().collect();
        ffi::connect::sql_driver_connect_w::<SqliteBackend>(
            conn,
            std::ptr::null_mut(),
            wide.as_ptr(),
            wide.len() as i16,
            std::ptr::null_mut(),
            0,
            std::ptr::null_mut(),
            0,
        )
    }
}

unsafe fn exec_direct(stmt: *mut c_void, sql: &str) -> SqlReturn {
    unsafe {
        let wide: Vec<u16> = sql.encode_utf16().collect();
        ffi::execute::sql_exec_direct_w::<SqliteBackend>(stmt, wide.as_ptr(), wide.len() as i32)
    }
}

unsafe fn cleanup(env: *mut c_void, conn: *mut c_void, stmt: *mut c_void) {
    unsafe {
        let _ = ffi::handle::sql_free_handle::<SqliteBackend>(HandleType::Stmt as i16, stmt);
        let _ = ffi::connect::sql_disconnect::<SqliteBackend>(conn);
        let _ = ffi::handle::sql_free_handle::<SqliteBackend>(HandleType::Dbc as i16, conn);
        let _ = ffi::handle::sql_free_handle::<SqliteBackend>(HandleType::Env as i16, env);
    }
}

/// Run setup SQL on `conn` through `SQLExecDirect`.
///
/// Setup goes through ODBC dispatch rather than reaching for the underlying
/// `rusqlite::Connection`, which core's `handles` module does not expose in any
/// case. Every setup here is three statements (`DROP`, `CREATE` and one bulk
/// `INSERT` whose rows are generated by a recursive CTE inside SQLite), so the
/// dispatch is paid three times, not once per row, and setup runs outside the
/// measured section regardless.
///
/// `SQLExecDirect` executes one statement, hence the split on `;`; none of the
/// generated setup SQL contains a `;` inside a string literal.
unsafe fn exec_setup(conn: *mut c_void, sql: &str) {
    unsafe {
        let mut stmt: *mut c_void = std::ptr::null_mut();
        let ret = ffi::handle::sql_alloc_handle::<SqliteBackend>(
            HandleType::Stmt as i16,
            conn,
            &mut stmt,
        );
        assert_eq!(ret, SqlReturn::SUCCESS, "alloc setup stmt");
        for one in sql.split(';').map(str::trim).filter(|s| !s.is_empty()) {
            let wide: Vec<u16> = one.encode_utf16().collect();
            let ret = ffi::execute::sql_exec_direct_w::<SqliteBackend>(
                stmt,
                wide.as_ptr(),
                wide.len() as i32,
            );
            assert_eq!(ret, SqlReturn::SUCCESS, "setup sql: {one}");
        }
        let _ = ffi::handle::sql_free_handle::<SqliteBackend>(HandleType::Stmt as i16, stmt);
    }
}

/// Build a `CREATE TABLE` + bulk `INSERT` for Shape A.
fn shape_a_setup_sql(rows: usize, cols: usize) -> String {
    let (n_i, n_s, n_d) = shape_a_split(cols);
    let mut col_defs: Vec<String> = Vec::with_capacity(cols);
    for i in 0..n_i {
        col_defs.push(format!("i{i} INTEGER"));
    }
    for i in 0..n_s {
        col_defs.push(format!("s{i} TEXT"));
    }
    for i in 0..n_d {
        col_defs.push(format!("d{i} TEXT"));
    }
    let create = format!(
        "DROP TABLE IF EXISTS bench_a; CREATE TABLE bench_a ({});",
        col_defs.join(", ")
    );

    // Generate the row data via SQLite's recursive CTE so we don't need 100k INSERT statements.
    let select_exprs: Vec<String> = {
        let mut v = Vec::with_capacity(cols);
        for i in 0..n_i {
            v.push(format!("(n + {i})"));
        }
        for _ in 0..n_s {
            v.push("'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'".into());
        }
        for _ in 0..n_d {
            v.push("'12345678.90'".into());
        }
        v
    };
    let insert = format!(
        "INSERT INTO bench_a SELECT {} FROM (
             WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n < {})
             SELECT n FROM seq
         );",
        select_exprs.join(", "),
        rows,
    );
    format!("{create} {insert}")
}

/// Build a `CREATE TABLE` + bulk `INSERT` for Shape B.
fn shape_b_setup_sql(rows: usize, str_len: usize) -> String {
    let s = "x".repeat(str_len);
    let create = "DROP TABLE IF EXISTS bench_b; CREATE TABLE bench_b (s0 TEXT, s1 TEXT, s2 TEXT, s3 TEXT, s4 TEXT);".to_string();
    let insert = format!(
        "INSERT INTO bench_b SELECT '{s}', '{s}', '{s}', '{s}', '{s}' FROM (
             WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n < {rows})
             SELECT n FROM seq
         );"
    );
    format!("{create} {insert}")
}

fn shape_a_select(cols: usize) -> String {
    let (n_i, n_s, n_d) = shape_a_split(cols);
    let mut names: Vec<String> = Vec::with_capacity(cols);
    for i in 0..n_i {
        names.push(format!("i{i}"));
    }
    for i in 0..n_s {
        names.push(format!("s{i}"));
    }
    for i in 0..n_d {
        names.push(format!("d{i}"));
    }
    format!("SELECT {} FROM bench_a", names.join(", "))
}

fn shape_b_select() -> String {
    "SELECT s0, s1, s2, s3, s4 FROM bench_b".to_string()
}

/// Late-binding drain: SQLFetch + per-cell SQLGetData into a discard buffer.
unsafe fn drain_late_binding(stmt: *mut c_void, n_cols: u16) -> usize {
    let mut buf = vec![0u8; 4096]; // generous per-cell scratch buffer
    let mut ind: isize = 0;
    let mut count = 0usize;
    while unsafe { ffi::fetch::sql_fetch::<SqliteBackend>(stmt) } == SqlReturn::SUCCESS {
        for col in 1..=n_cols {
            let _ = unsafe {
                ffi::fetch::sql_get_data::<SqliteBackend>(
                    stmt,
                    col,
                    CDataType::Default as i16,
                    buf.as_mut_ptr() as *mut c_void,
                    buf.len() as isize,
                    &mut ind,
                )
            };
            count += 1;
        }
    }
    count
}

/// One bound column: keeps its own scratch buffer and indicator alive across fetches.
struct BoundColumn {
    buf: Vec<u8>,
    ind: isize,
}

impl BoundColumn {
    fn new() -> Self {
        Self {
            buf: vec![0u8; 4096],
            ind: 0,
        }
    }
}

/// Bind every column once; returns the binding storage. Caller must keep the
/// returned Vec alive for as long as the bindings are in effect.
unsafe fn bind_columns(stmt: *mut c_void, n_cols: u16, c_type: CDataType) -> Vec<BoundColumn> {
    unsafe {
        let mut bindings: Vec<BoundColumn> = (0..n_cols).map(|_| BoundColumn::new()).collect();
        for (i, b) in bindings.iter_mut().enumerate() {
            let ret = ffi::bind::sql_bind_col::<SqliteBackend>(
                stmt,
                (i + 1) as u16,
                c_type as i16,
                b.buf.as_mut_ptr() as *mut c_void,
                b.buf.len() as isize,
                &mut b.ind,
            );
            assert_eq!(ret, SqlReturn::SUCCESS, "bind_col col {}", i + 1);
        }
        bindings
    }
}

/// Drain a result set whose columns have already been bound via `bind_columns`.
/// Returns total cells fetched (n_cols × n_rows).
unsafe fn drain_bound_columns(stmt: *mut c_void, n_cols: u16) -> usize {
    unsafe {
        let mut count = 0usize;
        while ffi::fetch::sql_fetch::<SqliteBackend>(stmt) == SqlReturn::SUCCESS {
            count += n_cols as usize;
        }
        count
    }
}

/// Same as `drain_late_binding` but call SQLGetData `repeats` times per cell.
unsafe fn drain_repeat_get_data(stmt: *mut c_void, n_cols: u16, repeats: usize) -> usize {
    unsafe {
        let mut buf = vec![0u8; 4096];
        let mut ind: isize = 0;
        let mut count = 0usize;
        while ffi::fetch::sql_fetch::<SqliteBackend>(stmt) == SqlReturn::SUCCESS {
            for col in 1..=n_cols {
                for _ in 0..repeats {
                    let _ = ffi::fetch::sql_get_data::<SqliteBackend>(
                        stmt,
                        col,
                        CDataType::Default as i16,
                        buf.as_mut_ptr() as *mut c_void,
                        buf.len() as isize,
                        &mut ind,
                    );
                    count += 1;
                }
            }
        }
        count
    }
}

fn bench_shape_a_late_binding(c: &mut Criterion) {
    let cfg = bench_config();
    let label = format!("{}x{}", cfg.rows, cfg.cols);
    let setup_sql = shape_a_setup_sql(cfg.rows, cfg.cols);
    let select_sql = shape_a_select(cfg.cols);

    // Set up the database once, outside the timed block.
    let (env, conn, stmt) = unsafe { alloc_handles() };
    assert_eq!(unsafe { connect_memory(conn) }, SqlReturn::SUCCESS);
    unsafe {
        exec_setup(conn, &setup_sql);
    }

    let mut group = c.benchmark_group("sqlite/shape_a");
    group.throughput(Throughput::Elements((cfg.rows * cfg.cols) as u64));
    group.bench_function(BenchmarkId::new("late_binding", &label), |b| {
        b.iter_batched(
            || unsafe {
                // Per-iter: close previous cursor and re-execute SELECT to get a fresh cursor.
                let _ = ffi::cursor::sql_close_cursor::<SqliteBackend>(stmt);
                assert_eq!(exec_direct(stmt, &select_sql), SqlReturn::SUCCESS);
            },
            |_| {
                black_box(unsafe { drain_late_binding(stmt, cfg.cols as u16) });
            },
            BatchSize::PerIteration,
        );
    });
    group.finish();

    unsafe {
        cleanup(env, conn, stmt);
    }
}

fn bench_shape_b_late_binding(c: &mut Criterion) {
    let cfg = bench_config();
    let label = format!("{}x5_len{}", cfg.wide_rows, cfg.wide_str_len);
    let setup_sql = shape_b_setup_sql(cfg.wide_rows, cfg.wide_str_len);
    let select_sql = shape_b_select();

    let (env, conn, stmt) = unsafe { alloc_handles() };
    assert_eq!(unsafe { connect_memory(conn) }, SqlReturn::SUCCESS);
    unsafe {
        exec_setup(conn, &setup_sql);
    }

    let mut group = c.benchmark_group("sqlite/shape_b");
    group.throughput(Throughput::Elements((cfg.wide_rows * 5) as u64));
    group.bench_function(BenchmarkId::new("late_binding", &label), |b| {
        b.iter_batched(
            || unsafe {
                let _ = ffi::cursor::sql_close_cursor::<SqliteBackend>(stmt);
                assert_eq!(exec_direct(stmt, &select_sql), SqlReturn::SUCCESS);
            },
            |_| {
                black_box(unsafe { drain_late_binding(stmt, 5) });
            },
            BatchSize::PerIteration,
        );
    });
    group.finish();

    unsafe {
        cleanup(env, conn, stmt);
    }
}

fn bench_shape_a_bound(c: &mut Criterion) {
    let cfg = bench_config();
    let label = format!("{}x{}", cfg.rows, cfg.cols);
    let setup_sql = shape_a_setup_sql(cfg.rows, cfg.cols);
    let select_sql = shape_a_select(cfg.cols);

    let (env, conn, stmt) = unsafe { alloc_handles() };
    assert_eq!(unsafe { connect_memory(conn) }, SqlReturn::SUCCESS);
    unsafe {
        exec_setup(conn, &setup_sql);
    }

    // Bind columns once, before the bench loop. Bindings survive SQLCloseCursor
    // per ODBC spec, so they remain in effect across all iterations.
    assert_eq!(
        unsafe { exec_direct(stmt, &select_sql) },
        SqlReturn::SUCCESS
    );
    let _bindings = unsafe { bind_columns(stmt, cfg.cols as u16, CDataType::Default) };
    let _ = unsafe { ffi::cursor::sql_close_cursor::<SqliteBackend>(stmt) };

    let mut group = c.benchmark_group("sqlite/shape_a");
    group.throughput(Throughput::Elements((cfg.rows * cfg.cols) as u64));
    group.bench_function(BenchmarkId::new("bound_columns", &label), |b| {
        b.iter_batched(
            || unsafe {
                let _ = ffi::cursor::sql_close_cursor::<SqliteBackend>(stmt);
                assert_eq!(exec_direct(stmt, &select_sql), SqlReturn::SUCCESS);
            },
            |_| {
                black_box(unsafe { drain_bound_columns(stmt, cfg.cols as u16) });
            },
            BatchSize::PerIteration,
        );
    });
    group.finish();

    unsafe {
        cleanup(env, conn, stmt);
    }
}

fn bench_shape_b_bound(c: &mut Criterion) {
    let cfg = bench_config();
    let label = format!("{}x5_len{}", cfg.wide_rows, cfg.wide_str_len);
    let setup_sql = shape_b_setup_sql(cfg.wide_rows, cfg.wide_str_len);
    let select_sql = shape_b_select();

    let (env, conn, stmt) = unsafe { alloc_handles() };
    assert_eq!(unsafe { connect_memory(conn) }, SqlReturn::SUCCESS);
    unsafe {
        exec_setup(conn, &setup_sql);
    }

    // Bind columns once, before the bench loop. Bindings survive SQLCloseCursor
    // per ODBC spec, so they remain in effect across all iterations.
    assert_eq!(
        unsafe { exec_direct(stmt, &select_sql) },
        SqlReturn::SUCCESS
    );
    // Use WChar for the wide-string shape so the bound buffer goes through the UTF-16 path.
    let _bindings = unsafe { bind_columns(stmt, 5, CDataType::WChar) };
    let _ = unsafe { ffi::cursor::sql_close_cursor::<SqliteBackend>(stmt) };

    let mut group = c.benchmark_group("sqlite/shape_b");
    group.throughput(Throughput::Elements((cfg.wide_rows * 5) as u64));
    group.bench_function(BenchmarkId::new("bound_columns", &label), |b| {
        b.iter_batched(
            || unsafe {
                let _ = ffi::cursor::sql_close_cursor::<SqliteBackend>(stmt);
                assert_eq!(exec_direct(stmt, &select_sql), SqlReturn::SUCCESS);
            },
            |_| {
                black_box(unsafe { drain_bound_columns(stmt, 5) });
            },
            BatchSize::PerIteration,
        );
    });
    group.finish();

    unsafe {
        cleanup(env, conn, stmt);
    }
}

fn bench_shape_a_repeat(c: &mut Criterion) {
    let cfg = bench_config();
    let label = format!("{}x{}", cfg.rows, cfg.cols);
    let setup_sql = shape_a_setup_sql(cfg.rows, cfg.cols);
    let select_sql = shape_a_select(cfg.cols);

    let (env, conn, stmt) = unsafe { alloc_handles() };
    assert_eq!(unsafe { connect_memory(conn) }, SqlReturn::SUCCESS);
    unsafe {
        exec_setup(conn, &setup_sql);
    }

    let mut group = c.benchmark_group("sqlite/shape_a");
    group.throughput(Throughput::Elements((cfg.rows * cfg.cols) as u64));
    let bench_id = BenchmarkId::new(format!("repeat_get_data_x{}", cfg.repeat_get_data), &label);
    group.bench_function(bench_id, |b| {
        b.iter_batched(
            || unsafe {
                let _ = ffi::cursor::sql_close_cursor::<SqliteBackend>(stmt);
                assert_eq!(exec_direct(stmt, &select_sql), SqlReturn::SUCCESS);
            },
            |_| {
                black_box(unsafe {
                    drain_repeat_get_data(stmt, cfg.cols as u16, cfg.repeat_get_data)
                });
            },
            BatchSize::PerIteration,
        );
    });
    group.finish();

    unsafe {
        cleanup(env, conn, stmt);
    }
}

fn bench_shape_b_repeat(c: &mut Criterion) {
    let cfg = bench_config();
    let label = format!("{}x5_len{}", cfg.wide_rows, cfg.wide_str_len);
    let setup_sql = shape_b_setup_sql(cfg.wide_rows, cfg.wide_str_len);
    let select_sql = shape_b_select();

    let (env, conn, stmt) = unsafe { alloc_handles() };
    assert_eq!(unsafe { connect_memory(conn) }, SqlReturn::SUCCESS);
    unsafe {
        exec_setup(conn, &setup_sql);
    }

    let mut group = c.benchmark_group("sqlite/shape_b");
    group.throughput(Throughput::Elements((cfg.wide_rows * 5) as u64));
    let bench_id = BenchmarkId::new(format!("repeat_get_data_x{}", cfg.repeat_get_data), &label);
    group.bench_function(bench_id, |b| {
        b.iter_batched(
            || unsafe {
                let _ = ffi::cursor::sql_close_cursor::<SqliteBackend>(stmt);
                assert_eq!(exec_direct(stmt, &select_sql), SqlReturn::SUCCESS);
            },
            |_| {
                black_box(unsafe { drain_repeat_get_data(stmt, 5, cfg.repeat_get_data) });
            },
            BatchSize::PerIteration,
        );
    });
    group.finish();

    unsafe {
        cleanup(env, conn, stmt);
    }
}

fn benches() -> Criterion {
    configure_for_size(Criterion::default(), bench_config().rows)
}

criterion_group! {
    name = benches_group;
    config = benches();
    targets =
        bench_shape_a_late_binding,
        bench_shape_b_late_binding,
        bench_shape_a_bound,
        bench_shape_b_bound,
        bench_shape_a_repeat,
        bench_shape_b_repeat
}
criterion_main!(benches_group);
