//! ODBC driver for [SQLite](https://sqlite.org), built on the generic
//! [`stackable_odbc_core`] framework.
//!
//! This crate compiles to a C dynamic library (`cdylib`) that an ODBC Driver
//! Manager (unixODBC on Linux, the built-in DM on Windows) loads at runtime.
//! It is not used as a normal Rust dependency. All the ODBC C ABI entry points
//! are generated by [`stackable_odbc_core::forward_ffi!`] from the [`SqliteBackend`]
//! implementation; the Driver Manager translates ANSI calls, so only the
//! Unicode (`W`) functions are exported.
//!
//! The backend opens a local SQLite database file through `rusqlite` (with the
//! bundled SQLite library). The database path is taken from the `Database`
//! connection-string key; `:memory:` opens an in-memory database. Because
//! SQLite is dynamically typed, column SQL types are inferred and its five
//! storage classes are mapped onto ODBC types.

mod backend;
mod escape_dialect;
mod type_conversion;

pub use backend::SqliteBackend;

stackable_odbc_core::forward_ffi!(crate::backend::SqliteBackend);

#[cfg(test)]
mod ffi_integration_tests;
