//! ODBC driver for [SQLite](https://sqlite.org), built on the generic
//! [`stackable_odbc_core`] framework.
//!
//! This crate compiles to a C dynamic library (`cdylib`) that an ODBC Driver
//! Manager (unixODBC on Linux, the built-in DM on Windows) loads at runtime.
//! It is not used as a normal Rust dependency. All the ODBC C ABI entry points
//! are generated by [`stackable_odbc_core::forward_ffi!`] from the [`SqliteBackend`]
//! implementation; the Driver Manager translates ANSI calls, so only the
//! Unicode (`W`) functions are exported.
//!
//! The backend opens a local SQLite database file through `rusqlite` (with the
//! bundled SQLite library). The database path is taken from the `Database`
//! connection-string key; `:memory:` opens an in-memory database. Because
//! SQLite is dynamically typed, column SQL types are inferred and its five
//! storage classes are mapped onto ODBC types.

mod backend;
mod escape_dialect;
mod type_conversion;

pub use backend::SqliteBackend;

stackable_odbc_core::forward_ffi!(crate::backend::SqliteBackend);

#[cfg(test)]
mod ffi_integration_tests;

#[cfg(test)]
mod packaging_tests {
    //! Checks that the shipped Windows setup dialog and the connection-string
    //! parser describe the same driver.
    //!
    //! The dialog is PowerShell and nothing compiles it, so a keyword added to
    //! one side and not the other would otherwise surface as a box a user can
    //! fill in that the driver then ignores, or as a setting reachable only by
    //! hand-editing the registry.

    /// Every connection-string keyword the parser accepts, from the `PARAM_`
    /// constants themselves rather than a transcribed list.
    fn connection_string_keys() -> Vec<&'static str> {
        let parser = include_str!("backend/types/connect_params.rs");
        // `pub(crate) const PARAM_DATABASE: &str = "database";`
        let mut keys: Vec<&str> = parser
            .lines()
            .filter_map(|line| {
                let rest = line.trim().strip_prefix("pub(crate) const PARAM_")?;
                let rest = rest.split_once(": &str = \"")?.1;
                rest.strip_suffix("\";")
            })
            .collect();
        keys.sort_unstable();
        keys
    }

    /// The dialog's `$Fields` table offers exactly the keywords the parser
    /// accepts, in both directions.
    ///
    /// Both sides are read from the files that ship rather than from a
    /// transcribed list, so adding a connection-string key fails here until
    /// the dialog offers it.
    #[test]
    fn dsn_keys_match_the_connection_string_parser() {
        let dialog = include_str!("../packaging/windows/configure-dsn.ps1");
        let parser_keys = connection_string_keys();
        assert!(
            !parser_keys.is_empty(),
            "expected the PARAM_ constants to parse; got {parser_keys:?}"
        );

        // `Key='database'` in the field table.
        let needle = "Key='";
        let mut dialog_keys: Vec<String> = dialog
            .match_indices(needle)
            .filter_map(|(i, _)| {
                let rest = &dialog[i + needle.len()..];
                rest.split_once('\'').map(|(v, _)| v.to_string())
            })
            .collect();
        dialog_keys.sort();

        let missing: Vec<&&str> = parser_keys
            .iter()
            .filter(|k| !dialog_keys.iter().any(|d| d == *k))
            .collect();
        assert!(
            missing.is_empty(),
            "connect_params.rs accepts {missing:?}, which configure-dsn.ps1's \
             field table does not offer; add an entry so Windows users can set it"
        );

        let unknown: Vec<&String> = dialog_keys
            .iter()
            .filter(|d| !parser_keys.iter().any(|k| k == *d))
            .collect();
        assert!(
            unknown.is_empty(),
            "configure-dsn.ps1 offers {unknown:?}, which connect_params.rs does \
             not accept; the driver would ignore it at connect"
        );
    }

    /// `packaging/sbom-native.json` declares the SQLite that is actually
    /// linked.
    ///
    /// SQLite is compiled into the driver from the amalgamation
    /// `libsqlite3-sys` vendors, so cargo — and therefore `cargo auditable`,
    /// syft and the SBOM — sees only the wrapper crate. The C library inside
    /// it is the component an advisory against SQLite would name, and the only
    /// place its version is written down is that fragment. A `libsqlite3-sys`
    /// bump changes the bundled version with nothing else to notice.
    ///
    /// `rusqlite::version()` is the linked library answering for itself, which
    /// is why it is the authority here rather than the crate version.
    #[test]
    fn the_declared_sqlite_version_is_the_one_linked() {
        let fragment = include_str!("../packaging/sbom-native.json");
        let linked = rusqlite::version();

        assert!(
            fragment.contains(&format!("\"version\": \"{linked}\"")),
            "sbom-native.json does not declare SQLite {linked}, which is what \
             rusqlite reports is linked in. Update the `common` entry's version \
             and purl; a release would otherwise ship an SBOM naming a SQLite \
             that is not in the binary."
        );
        assert!(
            fragment.contains(&format!("pkg:generic/sqlite@{linked}")),
            "sbom-native.json's SQLite purl does not name {linked}; the version \
             field and the purl have to move together"
        );
    }

    /// The dialog's `-DriverName` default is the name `install.bat` registers.
    ///
    /// Standalone, the script writes its data source through
    /// `SQLConfigDataSourceW` under that name, so a mismatch produces a data
    /// source pointing at a driver that is not installed. The two files are in
    /// different languages and neither is checked against the other by any
    /// toolchain.
    #[test]
    fn the_dialog_and_the_installer_agree_on_the_driver_name() {
        let dialog = include_str!("../packaging/windows/configure-dsn.ps1");
        let installer = include_str!("../packaging/windows/install.bat");

        let registered = installer
            .split_once("{INSTALLDRIVER \"")
            .and_then(|(_, rest)| rest.split_once('|'))
            .map(|(name, _)| name)
            .expect("install.bat registers a driver through odbcconf INSTALLDRIVER");

        assert!(
            dialog.contains(&format!("$DriverName = '{registered}'")),
            "install.bat registers {registered:?}, which is not configure-dsn.ps1's \
             default $DriverName; a data source written by the dialog would name a \
             driver that is not installed"
        );
    }
}
