#!/usr/bin/env python3
"""
BI stress tests for the SQLite ODBC driver.

Exercises the query patterns a BI tool emits, at a size the rest of the suite
does not reach: multi-table joins over a star schema, UNIONs, subqueries, CTEs,
window functions, large result sets and wide rows.

Where `test_sql_surface.py` asks whether a shape of SQL works at all, this asks
whether it still works over tens of thousands of rows. That matters more here
than for a client-server driver, because `exec_direct` materialises every row
before returning: a result set is held in memory in full, so a large one is the
case where that decision is felt. See the eager-materialisation section of
AGENTS.md.

The fixture is generated by recursive CTE rather than shipped, so the suite
carries no data file and the size is a constant at the top of this module.

There is no counterpart to the Trino driver's `parse_profile.py` and
`profile_stress.sh`. Those attribute a query's time between the coordinator and
the client, and SQLite has no server-side half: the query runs in-process,
inside the same shared object. `cargo bench` (`benches/fetch_sqlite.rs`) is
where fetch throughput is measured instead.

Usage:
    python3 integration-tests/perf/test_stress.py \
        "Driver=/path/to/libstackable_odbc_sqlite.so;Database=/path/to/test.db"
    python3 integration-tests/perf/test_stress.py "DSN=test_sqlite"

Needs no server. Requires `pyodbc`, normally through `uv run --with pyodbc`.
"""

import os
import sys

import pyodbc

sys.path.insert(
    0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "suites")
)

from harness import Results, Target  # noqa: E402

R = Results("stress")

CUSTOMERS = 5_000
ITEMS = 500
SALES = 50_000
# Customers above this have no sales, so a LEFT JOIN has NULLs to produce.
CUSTOMERS_WITH_SALES = 4_000

CUSTOMER = "stress_customer"
ITEM = "stress_item"
SALES_TABLE = "stress_sales"


def make_fixture(cur):
    """A small star schema, generated in three statements.

    Sales are dropped first and inserted last: the driver turns foreign-key
    enforcement on for every connection, so the order is not optional.
    """
    cur.execute(f"DROP TABLE IF EXISTS {SALES_TABLE}")
    cur.execute(f"DROP TABLE IF EXISTS {CUSTOMER}")
    cur.execute(f"DROP TABLE IF EXISTS {ITEM}")

    cur.execute(
        f"CREATE TABLE {CUSTOMER} ("
        "  id INTEGER PRIMARY KEY,"
        "  first_name TEXT,"
        "  last_name TEXT,"
        "  region TEXT"
        ")"
    )
    cur.execute(
        f"CREATE TABLE {ITEM} (id INTEGER PRIMARY KEY, product_name TEXT, category TEXT)"
    )
    cur.execute(
        f"CREATE TABLE {SALES_TABLE} ("
        "  id INTEGER PRIMARY KEY,"
        f" customer_id INTEGER REFERENCES {CUSTOMER}(id),"
        f" item_id INTEGER REFERENCES {ITEM}(id),"
        "  channel TEXT,"
        "  quantity INTEGER,"
        "  net_paid REAL"
        ")"
    )

    # Every tenth customer has a NULL last name, so the NULL probes have
    # something to find in a column that is not the join key.
    cur.execute(
        f"INSERT INTO {CUSTOMER} (id, first_name, last_name, region) "
        "WITH RECURSIVE seq(i) AS (SELECT 1 UNION ALL SELECT i + 1 FROM seq "
        f"WHERE i < {CUSTOMERS}) "
        "SELECT i, 'first' || i, "
        "CASE WHEN i % 10 = 0 THEN NULL ELSE 'last' || i END, "
        "'region' || (i % 10) FROM seq"
    )
    cur.execute(
        f"INSERT INTO {ITEM} (id, product_name, category) "
        "WITH RECURSIVE seq(i) AS (SELECT 1 UNION ALL SELECT i + 1 FROM seq "
        f"WHERE i < {ITEMS}) "
        "SELECT i, 'product' || i, 'category' || (i % 20) FROM seq"
    )
    cur.execute(
        f"INSERT INTO {SALES_TABLE} "
        "(id, customer_id, item_id, channel, quantity, net_paid) "
        "WITH RECURSIVE seq(i) AS (SELECT 1 UNION ALL SELECT i + 1 FROM seq "
        f"WHERE i < {SALES}) "
        f"SELECT i, (i % {CUSTOMERS_WITH_SALES}) + 1, (i % {ITEMS}) + 1, "
        "CASE WHEN i % 2 = 0 THEN 'store' ELSE 'web' END, "
        "(i % 7) + 1, "
        # Every hundredth sale has no amount, so the aggregates meet a NULL.
        "CASE WHEN i % 100 = 0 THEN NULL ELSE ((i % 1000) + 1) * 1.5 END "
        "FROM seq"
    )


def drop_fixture(cur):
    for table in (SALES_TABLE, CUSTOMER, ITEM):
        try:
            cur.execute(f"DROP TABLE IF EXISTS {table}")
        except Exception:  # noqa: BLE001
            pass


def main():
    target = Target.from_argv(
        sys.argv,
        "usage: test_stress.py "
        '"Driver=/path/to/libstackable_odbc_sqlite.so;Database=/path/to/test.db"',
    )
    conn = pyodbc.connect(target.conn_str(), autocommit=True)
    cur = conn.cursor()

    print(f"building the fixture: {CUSTOMERS} customers, {ITEMS} items, {SALES} sales")
    make_fixture(cur)

    try:
        # --------------------------------------------------------------
        # Multi-table joins
        # --------------------------------------------------------------
        def two_table_join():
            cur.execute(f"""
                SELECT c.first_name, c.last_name, SUM(s.net_paid) AS total_spend
                FROM {CUSTOMER} c
                JOIN {SALES_TABLE} s ON c.id = s.customer_id
                GROUP BY c.first_name, c.last_name
                ORDER BY total_spend DESC
                LIMIT 10
            """)
            rows = cur.fetchall()
            assert len(rows) == 10, f"expected 10 rows, got {len(rows)}"
            for row in rows:
                assert row[2] is not None and row[2] > 0, f"total_spend was {row[2]!r}"

        R.run("Two-table INNER JOIN with aggregation", two_table_join)

        def three_table_star_join():
            cur.execute(f"""
                SELECT c.first_name, i.product_name, SUM(s.quantity) AS total_qty
                FROM {SALES_TABLE} s
                JOIN {CUSTOMER} c ON s.customer_id = c.id
                JOIN {ITEM} i ON s.item_id = i.id
                GROUP BY c.first_name, i.product_name
                ORDER BY total_qty DESC
                LIMIT 10
            """)
            rows = cur.fetchall()
            assert len(rows) == 10, f"expected 10 rows, got {len(rows)}"
            for row in rows:
                assert row[2] is not None, "total_qty should not be NULL"

        R.run("Three-table star-schema JOIN", three_table_star_join)

        def left_join_nulls():
            cur.execute(f"""
                SELECT c.id, c.first_name, s.id
                FROM {CUSTOMER} c
                LEFT JOIN {SALES_TABLE} s ON c.id = s.customer_id
                WHERE c.id > {CUSTOMERS_WITH_SALES}
                ORDER BY c.id
                LIMIT 50
            """)
            rows = cur.fetchall()
            assert len(rows) == 50, f"expected 50 rows, got {len(rows)}"
            assert all(row[2] is None for row in rows), (
                "every customer past the sales range must join to NULL"
            )

        R.run("LEFT JOIN producing NULLs", left_join_nulls)

        # --------------------------------------------------------------
        # Subqueries and CTEs
        # --------------------------------------------------------------
        def in_subquery():
            cur.execute(f"""
                SELECT id, first_name FROM {CUSTOMER}
                WHERE id IN (
                    SELECT customer_id FROM {SALES_TABLE} WHERE net_paid > 1000
                )
                ORDER BY id
                LIMIT 10
            """)
            rows = cur.fetchall()
            assert len(rows) == 10, f"expected 10 rows, got {len(rows)}"
            for row in rows:
                assert row[0] > 0, f"id should be > 0, got {row[0]}"

        R.run("IN subquery over the fact table", in_subquery)

        def correlated_subquery():
            cur.execute(f"""
                SELECT c.id,
                       (SELECT COUNT(*) FROM {SALES_TABLE} s WHERE s.customer_id = c.id) AS n
                FROM {CUSTOMER} c
                WHERE c.id <= 20
                ORDER BY c.id
            """)
            rows = cur.fetchall()
            assert len(rows) == 20, f"expected 20 rows, got {len(rows)}"
            assert all(row[1] > 0 for row in rows), "each of these customers has sales"

        R.run("Correlated subquery", correlated_subquery)

        def cte():
            cur.execute(f"""
                WITH per_region AS (
                    SELECT c.region, SUM(s.net_paid) AS spend
                    FROM {CUSTOMER} c
                    JOIN {SALES_TABLE} s ON c.id = s.customer_id
                    GROUP BY c.region
                )
                SELECT region, spend FROM per_region ORDER BY spend DESC
            """)
            rows = cur.fetchall()
            assert len(rows) == 10, f"expected 10 regions, got {len(rows)}"

        R.run("CTE / WITH clause", cte)

        # --------------------------------------------------------------
        # Set operations
        # --------------------------------------------------------------
        def union_all():
            # Each branch is wrapped in a subquery because SQLite refuses a
            # LIMIT on an operand of a compound SELECT ("LIMIT clause should
            # come after UNION ALL not before"), where Trino accepts it. The
            # LIMIT has to bind per branch here, not to the union.
            cur.execute(f"""
                SELECT customer_id FROM (
                    SELECT customer_id FROM {SALES_TABLE}
                    WHERE channel = 'store' LIMIT 1000
                )
                UNION ALL
                SELECT customer_id FROM (
                    SELECT customer_id FROM {SALES_TABLE}
                    WHERE channel = 'web' LIMIT 1000
                )
            """)
            rows = cur.fetchall()
            assert len(rows) == 2000, f"expected 2000 rows, got {len(rows)}"

        R.run("UNION ALL across sales channels", union_all)

        def union_dedup():
            cur.execute(f"""
                SELECT region FROM {CUSTOMER}
                UNION
                SELECT region FROM {CUSTOMER}
            """)
            rows = cur.fetchall()
            assert len(rows) == 10, f"expected 10 distinct regions, got {len(rows)}"

        R.run("UNION with dedup", union_dedup)

        # --------------------------------------------------------------
        # Result-set shapes
        # --------------------------------------------------------------
        def large_result_set():
            cur.execute(f"SELECT id, customer_id, net_paid FROM {SALES_TABLE} ORDER BY id")
            rows = cur.fetchall()
            assert len(rows) == SALES, f"expected {SALES} rows, got {len(rows)}"
            # Ordered, so a dropped or duplicated row shows up as a gap rather
            # than only as a count that happens to match.
            assert rows[0][0] == 1 and rows[-1][0] == SALES, (
                f"first and last ids were {rows[0][0]} and {rows[-1][0]}"
            )

        R.run(f"Fetch all {SALES} rows", large_result_set)

        def wide_result_set():
            cur.execute(f"""
                SELECT s.id, s.customer_id, s.item_id, s.channel, s.quantity, s.net_paid,
                       c.first_name, c.last_name, c.region, i.product_name, i.category
                FROM {SALES_TABLE} s
                JOIN {CUSTOMER} c ON s.customer_id = c.id
                JOIN {ITEM} i ON s.item_id = i.id
                LIMIT 5000
            """)
            assert len(cur.description) == 11, (
                f"expected 11 columns, got {len(cur.description)}"
            )
            rows = cur.fetchall()
            assert len(rows) == 5000, f"expected 5000 rows, got {len(rows)}"
            assert len(rows[0]) == 11, f"expected 11 values, got {len(rows[0])}"

        R.run("Wide result set (11 columns)", wide_result_set)

        def nulls_in_various_positions():
            cur.execute(f"""
                SELECT id, last_name, region FROM {CUSTOMER}
                WHERE id % 10 = 0
                ORDER BY id
                LIMIT 100
            """)
            rows = cur.fetchall()
            assert len(rows) == 100, f"expected 100 rows, got {len(rows)}"
            assert all(row[1] is None for row in rows), (
                "every tenth customer has a NULL last name"
            )
            assert all(row[0] is not None and row[2] is not None for row in rows), (
                "the columns either side of the NULL must survive it"
            )

        R.run("NULLs in various column positions", nulls_in_various_positions)

        def empty_result_set():
            cur.execute(f"SELECT id FROM {CUSTOMER} WHERE id < 0")
            rows = cur.fetchall()
            assert rows == [], f"expected no rows, got {len(rows)}"
            # The describe still has to work: an application sizes its buffers
            # from it before it knows the set is empty.
            assert cur.description is not None, "an empty result set still has columns"

        R.run("Empty result set", empty_result_set)

        # --------------------------------------------------------------
        # Aggregation and windows at size
        # --------------------------------------------------------------
        def group_by_having_on_a_join():
            cur.execute(f"""
                SELECT c.region, COUNT(*) AS n, SUM(s.net_paid) AS spend
                FROM {CUSTOMER} c
                JOIN {SALES_TABLE} s ON c.id = s.customer_id
                GROUP BY c.region
                HAVING COUNT(*) > 100
                ORDER BY spend DESC
            """)
            rows = cur.fetchall()
            assert len(rows) == 10, f"expected 10 regions, got {len(rows)}"
            assert all(row[1] > 100 for row in rows), "HAVING was not applied"

        R.run("GROUP BY + HAVING on a JOIN", group_by_having_on_a_join)

        def window_function():
            cur.execute(f"""
                SELECT id, customer_id, rn FROM (
                    SELECT s.id, s.customer_id,
                           ROW_NUMBER() OVER (PARTITION BY s.customer_id ORDER BY s.id) AS rn
                    FROM {SALES_TABLE} s
                    WHERE s.customer_id <= 100
                )
                WHERE rn = 1
                ORDER BY customer_id
            """)
            rows = cur.fetchall()
            assert len(rows) == 100, f"expected 100 partitions, got {len(rows)}"
            assert all(row[2] == 1 for row in rows), "every row must be its partition's first"

        R.run("Window function (ROW_NUMBER OVER PARTITION BY)", window_function)

        # --------------------------------------------------------------
        # The parameter path, repeated
        # --------------------------------------------------------------
        def prepared_statement_reused():
            """A prepared statement re-executed many times.

            This is what a BI tool does when it pages through a dimension, and
            it is the path where a leak or a stale cursor would accumulate
            rather than show up once.
            """
            sql = f"SELECT COUNT(*) FROM {SALES_TABLE} WHERE customer_id = ?"
            total = 0
            for customer_id in range(1, 201):
                total += cur.execute(sql, [customer_id]).fetchone()[0]
            assert total > 0, "the repeated query found nothing"

        R.run("Prepared statement re-executed 200 times", prepared_statement_reused)
    finally:
        drop_fixture(cur)
        cur.close()
        conn.close()

    return R.summary()


if __name__ == "__main__":
    sys.exit(main())
